version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/kernel" # Location of package manifests
    schedule:
      interval: "weekly" 
  - package-ecosystem: "cargo" 
    directory: "/runner"
    schedule:
      interval: "weekly"
 - package-ecosystem: "cargo"
    directory: "/" 
    schedule:
      interval: "weekly"
